### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by windingwind** [windingwind/Knowledge4Zotero#3]
# Bugs
- [ ] export with images sometimes contains an extra string
- [ ] blank note page(on macOS?)

# Functions
- [ ] citation/info quick insert(#1 )
- [ ] note template(#1 )

# UI
- [ ] drag/drop improvment(#2 )
